// <auto-generated />
using BookShelf.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookShelf.Migrations
{
    [DbContext(typeof(BookShelfDbContext))]
    [Migration("20250202142640_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            modelBuilder.Entity("BookShelf.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books", "Library");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "F. Scott Fitzgerald",
                            CategoryId = 1,
                            Description = "Set during the Jazz Age on Long Island, this novel follows the mysterious Jay Gatsby and his obsessive pursuit of Daisy Buchanan, a woman he cannot have. The narrative explores the darker side of the American Dream, examining themes of love, wealth, and societal decay, with tragic consequences that ultimately reveal the emptiness behind materialism and ambition.",
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = 2,
                            Author = "George Orwell",
                            CategoryId = 1,
                            Description = "In George Orwell's dystopian vision, the Party's omnipresent surveillance and control over the masses create a society where truth is manipulated and free will is eliminated. Winston Smith, a worker in the Ministry of Truth, dares to question the totalitarian regime, leading him into a desperate search for freedom and the rediscovery of human integrity in a world where reality is distorted.",
                            Title = "1984"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Jane Austen",
                            CategoryId = 1,
                            Description = "Set in early 19th-century England, this novel tells the story of Elizabeth Bennet, an independent and sharp-witted woman who must navigate societal expectations and family pressures while grappling with her growing feelings for the proud Mr. Darcy. The book explores the complexities of love, marriage, and social class, illustrating how first impressions can be misleading and personal growth leads to understanding and acceptance.",
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Yuval Noah Harari",
                            CategoryId = 2,
                            Description = "Harari’s thought-provoking exploration of human history traces the evolution of Homo sapiens from hunter-gatherers to the rulers of the modern world. He examines how our species’ ability to create and share complex ideas has shaped societies, economies, and religions. With sharp insight, Harari challenges conventional views on progress, culture, and the future of humanity in the face of technological advancements.",
                            Title = "Sapiens: A Brief History of Humankind"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Sun Tzu",
                            CategoryId = 2,
                            Description = "An ancient Chinese military treatise, 'The Art of War' offers timeless principles of strategy and tactics that have influenced warfare, business, and leadership for centuries. Sun Tzu emphasizes the importance of preparation, adaptability, and psychological warfare in achieving victory. His teachings focus on the necessity of understanding both the enemy and oneself in order to outmaneuver adversaries and secure lasting success.",
                            Title = "The Art of War"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Michelle Obama",
                            CategoryId = 2,
                            Description = "In this deeply personal memoir, Michelle Obama shares the story of her life—from her childhood on the South Side of Chicago to becoming the First Lady of the United States. 'Becoming' explores her journey of self-discovery, tackling the complexities of identity, race, and motherhood. Through her candid reflections, she inspires readers to find their voice, face challenges, and believe in their potential to create change.",
                            Title = "Becoming"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Frank Herbert",
                            CategoryId = 3,
                            Description = "Set in a distant future, 'Dune' tells the story of Paul Atreides, a young nobleman who must navigate political intrigue, religious zealotry, and ecological challenges on the desert planet of Arrakis. As he struggles to claim his birthright and control the valuable spice melange, Paul is forced to confront the harsh realities of power, destiny, and survival in a world where loyalty and betrayal are never certain.",
                            Title = "Dune"
                        },
                        new
                        {
                            Id = 8,
                            Author = "William Gibson",
                            CategoryId = 3,
                            Description = "'Neuromancer' follows Case, a washed-up hacker, as he is hired by a mysterious employer to commit an illegal job that takes him deep into cyberspace. The novel, which helped define the cyberpunk genre, explores themes of artificial intelligence, virtual reality, and the blurred lines between the digital world and reality. As Case navigates a dangerous underworld of hackers, he faces the possibility of unlocking secrets that could reshape the future of humanity.",
                            Title = "Neuromancer"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Dan Simmons",
                            CategoryId = 3,
                            Description = "In 'Hyperion,' seven pilgrims journey to the distant world of Hyperion, each with their own story to tell. Their tales are rich with themes of love, war, religion, and existentialism, set against the backdrop of an epic interstellar conflict. The novel combines elements of classic science fiction with philosophical and theological explorations, weaving a complex narrative that examines humanity's search for meaning and the consequences of time and choice in a universe on the brink of destruction.",
                            Title = "Hyperion"
                        });
                });

            modelBuilder.Entity("BookShelf.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories", "Library");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = 2,
                            Name = "NonFiction"
                        },
                        new
                        {
                            Id = 3,
                            Name = "ScienceFiction"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Biography"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Thriller"
                        });
                });

            modelBuilder.Entity("BookShelf.Models.Book", b =>
                {
                    b.HasOne("BookShelf.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BookShelf.Models.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
